### ISSUE TITLE
Consolidate sleep fails in cases where the only sleep is a nap

### ISSUE THREAD

**Issue by lawreenas** [pelo-tech/whoop-google-sheets#7]
```
function v1_consolidate_sleeps(sleepArr){
  if(sleepArr.length==0) return {total_sleeps:0,total_naps:0};
  else {
    var sleeps=sleepArr.filter(s=>s.is_nap==false); <------- THIS FILTERS Array and sleeps can be []
    var naps=sleepArr.filter(s=>s.is_nap==true);
    var sleep= sleeps[0];  <-------- THIS makes sleep = undefined;
    sleep.total_sleeps=sleeps.length; <------ THIS gives Error
    sleep.total_naps=naps.length;
    return sleep;
  }
}
```

I suggest to change 
`    sleep.total_sleeps=sleeps.length;`
with 
`    var sleep= sleeps.length > 0 ? sleeps[0] : {};`

P.s. Thank you for the script ❤️

**Comment by DovOps** [comment]
@lawreenas  - Really embarrassed I just saw this now! - I made this exact change now due to someone else reporting it on the fb group. See Issue #8  and the associated merge. It fails  when the total sleeps is zero also, which is the case when someone uses a device for their first day. Bottom line, it's fixed now! Sorry for the delay.
